import { useEffect } from 'react';
import '../app/globals.css';
import { Fira_Sans } from 'next/font/google';
import Head from 'next/head';

const fira = Fira_Sans({ weight: '400', subsets: ['latin'] });

function MyApp({ Component, pageProps }) {
  useEffect(() => {
    if (process.env.NODE_ENV === 'development') {
      // debugger;
      // console.log('mock worker', worker)
      // worker && worker.start && worker.start();
    }
  }, []);

  return (
    <>
      <Head>
        <title>Kruzer Bookstore</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className={`alef ${fira.className} bg-customBackground min-h-screen`}>
        <Component {...pageProps} />
      </div>
    </>
  );
}

export default MyApp;
